version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Restoring NuGet packages...
      - dotnet restore
  build:
    commands:
      - echo Building the .NET 6 project...
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Running unit tests...
      - dotnet test --configuration Release --no-build
artifacts:
  files:
    - '**/*'
